name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  TZ: Asia/Tokyo

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: amd64
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.5"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o count-token-${{ matrix.goos }}-${{ matrix.goarch }} count-token.go

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            count-token-linux-amd64
            count-token-darwin-arm64
          tag_name: v1.0.0
          name: Release v1.0.0
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
